name: chatty
description: Blabber all night long with Chatty

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_shimmer: ^1.0.0
  app_settings: ^4.1.5
  camera: ^0.9.4+19
  cupertino_icons: ^1.0.4
  better_player: ^0.0.81
  bubble: ^1.2.1
  cached_network_image: ^3.2.0
  characters: ^1.2.0
  cloud_firestore: ^3.1.11
  confetti: ^0.6.0
  connectivity_plus: ^2.2.1
  device_info_plus: ^3.2.2
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.11
  flutter_local_notifications: ^9.4.0
  flutter_screenutil: ^5.3.1
  flutter_sound: ^9.1.9
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.3
  flutter_swipe_action_cell: ^2.2.0
  flutter_vibrate: ^1.3.0
  geolocator: ^8.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  just_audio: ^0.9.20
  like_button: ^2.0.4
  loading_animation_widget: ^1.1.0+3
  location: ^4.3.0
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  pin_code_fields: ^7.4.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.20
  video_compress: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 'flutter packages pub run build_runner build --delete-conflicting-outputs'
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.3+1
  hive_generator: ^1.1.2

# 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/some_icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/some_icon.png'

# 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/some_icon.png'

flutter:
  uses-material-design: true

 
  assets:
    - assets/icons/
    - assets/images/
