name: chatty
description: Blabber all night long with Chatty

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_shimmer: ^1.0.0
  app_settings: ^4.1.6
  camera: ^0.9.7+1
  cupertino_icons: ^1.0.4
  better_player: ^0.0.82
  bubble: ^1.2.1
  cached_network_image: ^3.2.1
  characters: ^1.2.1
  cloud_firestore: ^3.1.17
  confetti: ^0.7.0
  connectivity_plus: ^2.3.0
  device_info_plus: ^3.2.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter_local_notifications: ^9.5.3+1
  flutter_screenutil: ^5.5.3+2
  flutter_sound: ^9.2.13
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.0
  flutter_swipe_action_cell: ^3.0.2
  flutter_vibrate: ^1.3.0
  geolocator: ^8.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  just_audio: ^0.9.24
  like_button: ^2.0.4
  loading_animation_widget: ^1.2.0+1
  location: ^4.4.0
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  paginate_firestore: ^1.0.3+1
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  sliding_up_panel: ^2.0.0+1
  timeago: ^3.2.2
  url_launcher: ^6.1.2
  video_compress: ^3.1.0

dev_dependencies:
  # 'flutter packages pub run build_runner build --delete-conflicting-outputs'
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.2
  hive_generator: ^1.1.3

dependency_overrides:
  characters: ^1.2.1
  xml: ^6.1.0

# 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/some_icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/some_icon.png'

# 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/some_icon.png'

flutter:
  uses-material-design: true

 
  assets:
    - assets/icons/
    - assets/images/
